%hidden MODULE_NAME="coder_workspace"

set -ogq "@catppuccin_${MODULE_NAME}_icon" '󰒋 '
set -ogqF "@catppuccin_${MODULE_NAME}_color" '#{E:@thm_teal}'
set -ogq "@catppuccin_${MODULE_NAME}_text" '#{l:$CODER_WORKSPACE_NAME}'

source -F '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/utils/status_module.conf'
